tempo:
  tempo:
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
    
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317
      jaeger:
        protocols:
          thrift_http:
            endpoint: 0.0.0.0:14268
          grpc:
            endpoint: 0.0.0.0:14250
      zipkin:
        endpoint: 0.0.0.0:9411
  
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 10Gi
  
  service:
    type: ClusterIP
