apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-{{ .Values.environment }}-config
  labels:
    app: weather
    environment: {{ .Values.environment }}
data:
  APP_ENV: {{ .Values.environment }}
  LOG_LEVEL: {{ .Values.logLevel | default "info" | quote }}
  WEATHER_API_URL: {{ .Values.weatherApiUrl | quote }}
  WEATHER_LOCATION: {{ .Values.weatherLocation | quote }}
  WEATHER_Q: {{ .Values.weatherQ | quote }}
  PORT: {{ .Values.port | default "3001" | quote }}
  # PostgreSQL connection (ตรงกับ code)
  POSTGRES_HOST: "postgresql-0.postgresql.postgresql.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "weather-{{ .Values.environment }}"
  
  # Tempo tracing
  TEMPO_URL: "http://tempo-production:4318/v1/traces"

