apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-{{ .Values.environment }}
  labels:
    app: weather
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: bankt21/weather-ingest:{{ .Values.imageTag | default "v11" }}
        ports:
        - containerPort: 3001
        envFrom:
          - configMapRef:
              name: weather-{{ .Values.environment }}-config
          - secretRef:
              name: weather-{{ .Values.environment }}-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
