apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-{{ .Values.environment }}
  labels:
    app: weather-app
    environment: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: weather-app
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: weather-app
        environment: {{ .Values.environment }}
    spec:
      containers:
      - name: weather-app
        image: bankt21/weather-ingest:{{ .Values.imageTag | default "v11" }}
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        envFrom:
          - configMapRef:
              name: weather-{{ .Values.environment }}-config
          - secretRef:
              name: weather-{{ .Values.environment }}-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
