apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weather-{{ .Values.environment }}-secret
  labels:
    app: weather
    environment: {{ .Values.environment }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-{{ .Values.environment }}
    kind: ClusterSecretStore
  target:
    name: weather-{{ .Values.environment }}-secret
    creationPolicy: Owner
  data:
    - secretKey: WEATHER_API_KEY
      remoteRef:
        key: "{{ .Values.environment }}/weather-app"
        property: WEATHER_API_KEY
    - secretKey: POSTGRES_USER
      remoteRef:
        key: "production/postgresql"
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: "production/postgresql"
        property: password


