apiVersion: v1
kind: Service
metadata:
  name: weather-{{ .Values.environment }}-service
  labels:
    app: weather-app
    environment: {{ .Values.environment }}
spec:
  type: ClusterIP
  selector:
    app: weather-app
    environment: {{ .Values.environment }}
  ports:
  - name: http
    protocol: TCP
    port: 3001
    targetPort: 3001
