apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://10.245.0.11:8200"
      path: "cubbyhole"
      version: "v1"
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: external-secrets
          key: token
