apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/theerawatzuz/agnos.git
    targetRevision: production
    path: 03-argocd-apps/manifests/postgresql
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
