apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: weather
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: weather-dev
            branch: dev
          - env: uat
            namespace: weather-uat
            branch: uat
          - env: production
            namespace: weather-production
            branch: production
  template:
    metadata:
      name: "weather-{{env}}"
    spec:
      project: "default"
      source:
        repoURL: https://github.com/theerawatzuz/agnos.git
        targetRevision: production # ใช้ production branch เดียว
        path: "03-argocd-apps/manifests/app-weather"
        helm:
          valueFiles:
            - values.yaml
            - values-{{env}}.yaml
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
