apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-production
    kind: ClusterSecretStore
  target:
    name: postgresql-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: kv/production/postgresql
        property: username
    - secretKey: password
      remoteRef:
        key: kv/production/postgresql
        property: password
