apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  clusterIP: None
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-0
spec:
  type: NodePort
  selector:
    app: postgresql
    statefulset.kubernetes.io/pod-name: postgresql-0
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
      name: postgresql
